import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft, ArrowUpRight, Check, Code2, Package, ShieldCheck } from "lucide-react";
import { SiteFooter, SiteHeader } from "../../components/site-header";
import { REPOSITORY_URL } from "../../lib/catalog";

export const metadata: Metadata = { title: "Build a plugin" };

export default function DocsPage() {
  return <><SiteHeader /><main className="page-shell"><div className="container" style={{ maxWidth: 860 }}><div className="breadcrumbs"><Link href="/"><ArrowLeft size={14} /> Home</Link><span>/</span><span>Build a plugin</span></div><div className="page-heading" style={{ display: "block" }}><p className="section-kicker">For builders</p><h1>Build a plugin.</h1><p>PI-Desktop plugins are small, versioned packages that add tools, panels, skills and workflows to a local workspace.</p></div><div className="trust-grid" style={{ marginTop: 40, gridTemplateColumns: "repeat(3, 1fr)" }}><div className="trust-item"><span className="trust-number">01</span><h3><Code2 size={17} /> Start from a template</h3><p>Copy the practical workspace summary template or the smallest Hello example.</p></div><div className="trust-item"><span className="trust-number">02</span><h3><ShieldCheck size={17} /> Request only what you need</h3><p>Permissions are reviewed by users and should be kept as narrow as possible.</p></div><div className="trust-item"><span className="trust-number">03</span><h3><Package size={17} /> Pack and publish</h3><p>Build a .piplug package, rebuild the catalog, then open a pull request.</p></div></div><article className="detail-content"><h2>Quick start</h2><pre><code>{`git clone https://github.com/<you>/pi-desktop-plugins.git\ncd pi-desktop-plugins\ncp -R plugins/demo.workspace-summary plugins/my.plugin-id\n\n# edit manifest.json, main.js and README.md\npython3 scripts/pack_plugin.py plugins/my.plugin-id\npython3 scripts/rebuild_catalog.py`}</code></pre><h2>What makes a good plugin?</h2><ul><li>Clear README explaining what the plugin does and what it can access.</li><li>Semantic versioning and a short changelog for every published version.</li><li>A minimum permission set with plain-language safety notes.</li><li>Localized panel titles when a plugin provides a UI panel.</li></ul><h2>Submit to the catalog</h2><p>Follow the full contribution checklist in the repository. Once merged, the raw catalog and package become available to PI-Desktop users.</p><p><a className="button primary-button" href={`${REPOSITORY_URL}/blob/main/CONTRIBUTING.md`} target="_blank" rel="noreferrer">Read CONTRIBUTING.md <ArrowUpRight size={15} /></a></p><h2>Local verification</h2><p>Load the development plugin in PI-Desktop, confirm its commands and panels, inspect the permission behavior, then test the packaged .piplug artifact before opening a pull request.</p><div className="aside-card" style={{ marginTop: 28 }}><Check size={17} color="var(--green)" /><p className="safety-note" style={{ margin: "8px 0 0" }}>The official catalog is intentionally source-first: read the manifest and README before installing.</p></div></article></div></main><SiteFooter /></>;
}
