const SKIP = new Set([
  ".git",
  "node_modules",
  "target",
  "dist",
  "build",
  ".next",
  ".cache",
  "out",
  "coverage",
]);

async function listTopLevel(includeDotfiles, maxEntries) {
  const entries = await pi.fs.glob("*");
  const files = [];
  for (const rel of entries) {
    if (rel.includes("/")) continue;
    if (!includeDotfiles && rel.startsWith(".")) continue;
    if (SKIP.has(rel)) continue;
    files.push(rel);
    if (files.length >= maxEntries) break;
  }
  files.sort((a, b) => a.localeCompare(b));
  return files;
}

async function readReadme() {
  for (const name of ["README.md", "README.MD", "Readme.md", "readme.md"]) {
    try {
      const text = await pi.fs.readText(name);
      return { name, text };
    } catch {
      // try next
    }
  }
  return null;
}

function excerpt(text, max = 600) {
  const normalized = String(text || "").replace(/\r\n/g, "\n").trim();
  if (normalized.length <= max) return normalized;
  return `${normalized.slice(0, max).trimEnd()}\n…`;
}

async function buildSummary(options = {}) {
  const settings = await pi.plugin.getSettings();
  const maxEntries = Number(options.maxEntries ?? settings.maxEntries ?? 30) || 30;
  const includeDotfiles = Boolean(
    options.includeDotfiles ?? settings.includeDotfiles ?? false,
  );
  const workspace = await pi.workspace.get();
  const topLevel = await listTopLevel(includeDotfiles, maxEntries);
  const allFiles = await pi.fs.glob("**/*");
  const visibleFiles = allFiles.filter((rel) => {
    const parts = rel.split("/");
    if (parts.some((p) => SKIP.has(p))) return false;
    if (!includeDotfiles && parts.some((p) => p.startsWith("."))) return false;
    return true;
  });
  const readme = await readReadme();
  const summary = {
    ok: true,
    pluginId: pi.plugin.getId(),
    workspace: workspace
      ? { path: workspace.path, name: workspace.name }
      : null,
    topLevelCount: topLevel.length,
    topLevel,
    fileCount: visibleFiles.length,
    readmeName: readme?.name ?? null,
    readmeExcerpt: readme ? excerpt(readme.text) : null,
    generatedAt: new Date().toISOString(),
  };
  return summary;
}

function formatText(summary) {
  if (!summary.workspace) {
    return "No workspace is open.";
  }
  const lines = [
    `# Workspace Summary`,
    "",
    `- Project: ${summary.workspace.name}`,
    `- Path: ${summary.workspace.path}`,
    `- Top-level entries: ${summary.topLevelCount}`,
    `- Approximate file count: ${summary.fileCount}`,
    "",
    "## Top-level",
    ...summary.topLevel.map((name) => `- ${name}`),
  ];
  if (summary.readmeName) {
    lines.push("", `## ${summary.readmeName}`, "", summary.readmeExcerpt || "");
  }
  lines.push("", `_Generated by demo.workspace-summary at ${summary.generatedAt}_`);
  return lines.join("\n");
}

async function onLoad() {
  await pi.commands.register({
    id: "summary.open",
    title: "Workspace: Open Summary",
    keywords: ["summary", "workspace", "inventory", "template"],
    category: "Productivity",
    run: async () => {
      await pi.ui.openPanel({ title: "Workspace Summary" });
    },
  });

  await pi.agent.registerTool({
    name: "workspace_summary",
    description:
      "Summarize the current workspace: top-level entries, README excerpt, and rough file counts.",
    risk: "medium",
    schema: {
      type: "object",
      properties: {
        maxEntries: {
          type: "number",
          description: "Max top-level entries to include (default 30)",
        },
      },
    },
    execute: async (args = {}) => {
      const summary = await buildSummary(args);
      return {
        ...summary,
        text: formatText(summary),
      };
    },
  });
}

async function onUnload() {
  await pi.commands.unregister("summary.open");
  await pi.agent.unregisterTool("workspace_summary");
}

module.exports = {
  onLoad,
  onUnload,
  // Exported for panel bridge convenience in future hosts.
  __template: {
    buildSummary,
    formatText,
  },
};
